"""Finite groups and exact finite-field representations."""

from .errors import (
    ConcreteEmbeddingError,
    InvalidActionError,
    NonSemisimpleError,
    NonSplitRepresentationError,
    RepresentationError,
)
from .group import (
    CyclicGroup,
    FinitePermutationGroup,
    GenerationCertificate,
    GenerationWitness,
    GeneratorStep,
    PermutationGroup,
    cyclic_group,
    symmetric_group,
)
from .maps import FiniteGroupExtension, FiniteGroupMap
from .permutation import Permutation
from .representation import (
    Character,
    CyclicComponent,
    CyclicDecomposition,
    CyclicFactor,
    IsotypicComponent,
    IsotypicDecomposition,
    Representation,
    RepresentationValidation,
    SemisimplicityResult,
    WeightDecomposition,
    decompose,
    fixed_part,
    isotypic,
    projector,
    representation,
    semisimple,
    weight_spaces,
)

__all__ = [
    "Character",
    "ConcreteEmbeddingError",
    "CyclicComponent",
    "CyclicDecomposition",
    "CyclicFactor",
    "CyclicGroup",
    "FiniteGroupExtension",
    "FiniteGroupMap",
    "FinitePermutationGroup",
    "GenerationCertificate",
    "GenerationWitness",
    "GeneratorStep",
    "InvalidActionError",
    "IsotypicComponent",
    "IsotypicDecomposition",
    "NonSemisimpleError",
    "NonSplitRepresentationError",
    "Permutation",
    "PermutationGroup",
    "Representation",
    "RepresentationError",
    "RepresentationValidation",
    "SemisimplicityResult",
    "WeightDecomposition",
    "cyclic_group",
    "decompose",
    "fixed_part",
    "isotypic",
    "projector",
    "representation",
    "semisimple",
    "symmetric_group",
    "weight_spaces",
]
