"""Finite exact Nielsen classes, braid actions, and Hurwitz arithmetic.

No operation in this module silently changes a concrete group embedding.
Imported representative datasets remain explicitly distinct from exhaustive
enumeration certificates.
"""

from __future__ import annotations

from .boundary import (
    BoundaryCollisionWitness,
    BoundaryIncidence,
    BoundaryIncidenceCertificate,
    BoundaryStratum,
    BoundaryTuple,
    Collision,
    boundary,
    boundary_incidence,
    collide,
)
from .braid import (
    BraidAction,
    BraidEdgeCertificate,
    BraidMove,
    BraidPath,
    BraidPathStep,
    BraidWord,
    ComponentCollection,
    HurwitzComponent,
    NamedBraidGenerator,
    SpanningTreeCertificate,
    SpanningTreeEdge,
    apply_braid_word,
    apply_braid_word_entries,
    braid_action,
    braid_distance,
    components,
    hurwitz_move,
    pure_braid_word,
    weighted_braid_path,
)
from .claims import (
    claim_for,
    claim_graph_for,
    register_hurwitz_replay,
    verification_certificate_for,
)
from .dataset import (
    PRECOMPUTED_NIELSEN_SCHEMA,
    ImportedNielsenDataset,
    load_precomputed_nielsen_class,
)
from .errors import (
    BraidClosureError,
    CertificateVerificationError,
    ConcreteGroupMismatchError,
    GroupProtocolError,
    HurwitzError,
    ImportedBoundaryError,
    InvalidConjugacyClassError,
    InvalidNielsenTupleError,
    UnsupportedHurwitzOperation,
)
from .geometry import (
    Cusp,
    CuspCertificate,
    CuspData,
    ExplicitSymmetry,
    ReducedComponent,
    ReducedQuotientCertificate,
    SourceGenusCertificate,
    SourceGenusResult,
    cusps,
    reduced,
    source_genus,
    source_genus_result,
    symmetry_from_braid_word,
)
from .m23_exact import (
    DATASET_SCHEMA as M23_EXACT_DATASET_SCHEMA,
)
from .m23_exact import (
    M23_EXACT_CERTIFICATE_SCHEMA,
    M23_EXACT_VERIFIER,
    M23ExactCertificate,
    M23ExactDataset,
    M23ExactVerification,
    M23ExactVerificationError,
    load_m23_exact_dataset,
    m23_certificates_for,
    m23_claim_graph_for,
    m23_verification_certificate_for,
    m23_verifier_registry,
)
from .m23_exact import (
    MANIFEST_SCHEMA as M23_EXACT_MANIFEST_SCHEMA,
)
from .nielsen import (
    CanonicalizationWitness,
    ExplicitConjugacyClass,
    ImportedNielsenBoundary,
    InnerOrbitWitness,
    NielsenClass,
    NielsenEnumerationCertificate,
    NielsenEnumerationPlan,
    NielsenShardResult,
    NielsenShardSpec,
    NielsenTuple,
    nielsen_class,
    nielsen_tuple,
    plan_nielsen_class,
    verify_nielsen_certificate_payload,
)
from .portable import (
    PORTABLE_OPERATION_SCHEMA,
    PORTABLE_OPERATIONS,
    HurwitzOperationCertificate,
    operation_certificate_for,
    verify_hurwitz_operation_payload,
)
from .real import (
    RealCensus,
    RealPointWitness,
    RealStructure,
    RealStructureCertificate,
    is_real_tuple,
    is_totally_real,
    real_census,
    real_points,
    real_structure,
    real_witnesses,
    signed_slot_transform,
    straight_real_transform,
    totally_real,
)

__all__ = [
    "M23_EXACT_CERTIFICATE_SCHEMA",
    "M23_EXACT_DATASET_SCHEMA",
    "M23_EXACT_MANIFEST_SCHEMA",
    "M23_EXACT_VERIFIER",
    "PORTABLE_OPERATIONS",
    "PORTABLE_OPERATION_SCHEMA",
    "PRECOMPUTED_NIELSEN_SCHEMA",
    "BoundaryCollisionWitness",
    "BoundaryIncidence",
    "BoundaryIncidenceCertificate",
    "BoundaryStratum",
    "BoundaryTuple",
    "BraidAction",
    "BraidClosureError",
    "BraidEdgeCertificate",
    "BraidMove",
    "BraidPath",
    "BraidPathStep",
    "BraidWord",
    "CanonicalizationWitness",
    "CertificateVerificationError",
    "Collision",
    "ComponentCollection",
    "ConcreteGroupMismatchError",
    "Cusp",
    "CuspCertificate",
    "CuspData",
    "ExplicitConjugacyClass",
    "ExplicitSymmetry",
    "GroupProtocolError",
    "HurwitzComponent",
    "HurwitzError",
    "HurwitzOperationCertificate",
    "ImportedBoundaryError",
    "ImportedNielsenBoundary",
    "ImportedNielsenDataset",
    "InnerOrbitWitness",
    "InvalidConjugacyClassError",
    "InvalidNielsenTupleError",
    "M23ExactCertificate",
    "M23ExactDataset",
    "M23ExactVerification",
    "M23ExactVerificationError",
    "NamedBraidGenerator",
    "NielsenClass",
    "NielsenEnumerationCertificate",
    "NielsenEnumerationPlan",
    "NielsenShardResult",
    "NielsenShardSpec",
    "NielsenTuple",
    "RealCensus",
    "RealPointWitness",
    "RealStructure",
    "RealStructureCertificate",
    "ReducedComponent",
    "ReducedQuotientCertificate",
    "SourceGenusCertificate",
    "SourceGenusResult",
    "SpanningTreeCertificate",
    "SpanningTreeEdge",
    "UnsupportedHurwitzOperation",
    "apply_braid_word",
    "apply_braid_word_entries",
    "boundary",
    "boundary_incidence",
    "braid_action",
    "braid_distance",
    "claim_for",
    "claim_graph_for",
    "collide",
    "components",
    "cusps",
    "hurwitz_move",
    "is_real_tuple",
    "is_totally_real",
    "load_m23_exact_dataset",
    "load_precomputed_nielsen_class",
    "m23_certificates_for",
    "m23_claim_graph_for",
    "m23_verification_certificate_for",
    "m23_verifier_registry",
    "nielsen_class",
    "nielsen_tuple",
    "operation_certificate_for",
    "plan_nielsen_class",
    "pure_braid_word",
    "real_census",
    "real_points",
    "real_structure",
    "real_witnesses",
    "reduced",
    "register_hurwitz_replay",
    "signed_slot_transform",
    "source_genus",
    "source_genus_result",
    "straight_real_transform",
    "symmetry_from_braid_word",
    "totally_real",
    "verification_certificate_for",
    "verify_hurwitz_operation_payload",
    "verify_nielsen_certificate_payload",
    "weighted_braid_path",
]
