"""Lean-facing proof-obligation export with no backend-specific encodings."""

from __future__ import annotations

import re

from arbogast.claims import Claim, ClaimDomain, ClaimGraph
from arbogast.claims.statement import StatementError
from arbogast.formats import CLAIM_SCHEMA_V2
from arbogast.proof import ProofGap, ProofObligation

from ._domains import DomainFilter, domain_label, normalize_domains, select_claims
from ._lifting import claim_graph_for_export

_LEAN_KEYWORDS = frozenset(
    {
        "abbrev",
        "axiom",
        "by",
        "class",
        "def",
        "deriving",
        "do",
        "else",
        "end",
        "example",
        "export",
        "extends",
        "for",
        "forall",
        "fun",
        "if",
        "import",
        "in",
        "inductive",
        "infix",
        "infixl",
        "infixr",
        "instance",
        "let",
        "macro",
        "match",
        "mutual",
        "namespace",
        "opaque",
        "open",
        "partial",
        "private",
        "protected",
        "public",
        "return",
        "set_option",
        "structure",
        "syntax",
        "theorem",
        "variable",
        "where",
        "with",
    }
)


def export_lean(
    value: object,
    *,
    namespace: str = "Arbogast.Generated",
    domains: DomainFilter = None,
) -> str:
    selected_domains = normalize_domains(domains)
    lifted = claim_graph_for_export(value)
    if lifted is not None:
        value = lifted
    claims = _claims(value, selected_domains)
    obligations = _obligations(value, claims)
    nonmathematical_obligations = _nonmathematical_obligation_ids(claims)
    _require_unique_generated_names(obligations, claims)
    namespace_parts = namespace.split(".")
    if any(
        not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", item) or item in _LEAN_KEYWORDS
        for item in namespace_parts
    ):
        raise ValueError(f"invalid Lean namespace: {namespace!r}")
    if not isinstance(value, (Claim, ClaimGraph, ProofGap, ProofObligation)):
        raise TypeError(f"Lean export does not support {type(value).__qualname__}")
    lines = [
        "/- Generated by Arbogast. Discovery backends are intentionally absent. -/",
        "/- This obligation projection is not a replayable certificate bundle; use JSON. -/",
        f"namespace {namespace}",
        "",
        "structure ProofObligationData where",
        "  id : String",
        "  statement : String",
        "  classification : String",
        "  context : List String",
        "  dependencies : List String",
        "  evidence : List String",
        "  dischargedBy : List String",
        "  notes : Option String",
        "  deriving Repr, DecidableEq",
        "",
        "def proofObligations : List ProofObligationData := [",
    ]
    if selected_domains is not None:
        lines[3:3] = [f"/- Domain projection: {domain_label(selected_domains)}. -/", ""]
    for index, obligation in enumerate(obligations):
        comma = "," if index + 1 < len(obligations) else ""
        lines.extend(
            [
                "  {",
                f'    id := "{_lean_string(obligation.id)}"',
                f'    statement := "{_lean_string(obligation.statement.text)}"',
                f'    classification := "{obligation.classification.value}"',
                f"    context := {_lean_statement_text_list(obligation.context)}",
                f"    dependencies := {_lean_string_list(obligation.dependencies)}",
                f"    evidence := {_lean_string_list(obligation.evidence)}",
                f"    dischargedBy := {_lean_string_list(obligation.discharged_by)}",
                f"    notes := {_lean_optional_string(obligation.notes)}",
                f"  }}{comma}",
            ]
        )
    lines.extend(["]", ""])
    for obligation in obligations:
        if obligation.id in nonmathematical_obligations:
            lines.append(
                f"-- obligation {obligation.id} axiom omitted: owning claim domain "
                "is not mathematical"
            )
            continue
        proposition = _conditional_lean_proposition(
            obligation.context,
            obligation.statement,
        )
        if proposition is not None:
            lines.append(f"axiom obligation_{_lean_name(obligation.id)} : {proposition}")
        elif _lean_proposition(obligation.statement) is not None and obligation.context:
            lines.append(
                f"-- obligation {obligation.id} omitted: a context statement has no explicit "
                "Lean rendering"
            )
    if obligations:
        lines.append("")
    for claim in claims:
        lean_name = _lean_name(claim.id)
        lines.append(f'def claimData_{lean_name} : String := "{_lean_string(claim.id)}"')
        if claim.schema_version == CLAIM_SCHEMA_V2:
            lines.append(f'def claimDomain_{lean_name} : String := "{claim.domain.value}"')
        lines.append(
            f"def claimHypotheses_{lean_name} : List String := "
            f"{_lean_statement_text_list(claim.hypotheses)}"
        )
        boundary = f"{claim.kind.value}/{claim.status.value}"
        if claim.schema_version == CLAIM_SCHEMA_V2:
            boundary = f"{claim.domain.value}/{boundary}"
        lines.append(f"-- claim {claim.id} [{boundary}]: {_comment(claim.what.text)}")
        if claim.domain is not ClaimDomain.MATHEMATICAL:
            lines.append(
                f"-- claim {claim.id} axiom omitted: domain {claim.domain.value} "
                "is not mathematical"
            )
            continue
        proposition = _conditional_lean_proposition(claim.hypotheses, claim.what)
        if proposition is not None:
            lines.append(f"axiom claim_{lean_name} : {proposition}")
        elif _lean_proposition(claim.what) is not None and claim.hypotheses:
            lines.append(
                f"-- claim {claim.id} axiom omitted: a hypothesis has no explicit Lean rendering"
            )
    lines.extend(["", f"end {namespace}", ""])
    return "\n".join(lines)


def _obligations(
    value: object,
    claims: tuple[Claim, ...],
) -> tuple[ProofObligation, ...]:
    if isinstance(value, ProofGap):
        return value.obligations
    if isinstance(value, ProofObligation):
        return (value,)
    if isinstance(value, (ClaimGraph, Claim)):
        return tuple(obligation for claim in claims for obligation in _claim_obligations(claim))
    return ()


def _nonmathematical_obligation_ids(claims: tuple[Claim, ...]) -> frozenset[str]:
    return frozenset(
        obligation.id
        for claim in claims
        if claim.domain is not ClaimDomain.MATHEMATICAL
        for obligation in _claim_obligations(claim)
    )


def _claim_obligations(claim: Claim) -> tuple[ProofObligation, ...]:
    """Qualify claim-local obligation IDs for collision-free graph projection."""

    if claim.formalization is None:
        return ()
    # Length-prefixing makes the owner/local join injective even though both ID
    # grammars permit ``/`` (``claim/a`` + ``b`` must differ from ``claim`` + ``a/b``).
    prefix = f"owned/{len(claim.id)}:{claim.id}/"
    return tuple(
        ProofObligation(
            id=prefix + obligation.id,
            statement=obligation.statement,
            classification=obligation.classification,
            context=obligation.context,
            dependencies=tuple(prefix + item for item in obligation.dependencies),
            evidence=obligation.evidence,
            discharged_by=obligation.discharged_by,
            notes=obligation.notes,
        )
        for obligation in claim.formalization.obligations
    )


def _claims(
    value: object,
    domains: frozenset[ClaimDomain] | None,
) -> tuple[Claim, ...]:
    if isinstance(value, ClaimGraph):
        return select_claims(value, domains)
    if isinstance(value, Claim):
        return select_claims((value,), domains)
    return ()


def _lean_proposition(statement: object) -> str | None:
    render = getattr(statement, "render", None)
    if not callable(render):
        return None
    try:
        proposition = render("lean", fallback=False)
    except StatementError:
        return None
    return proposition if isinstance(proposition, str) and proposition.strip() else None


def _conditional_lean_proposition(
    context: tuple[object, ...],
    conclusion: object,
) -> str | None:
    """Render an implication only when every proposition was supplied explicitly.

    Falling back from mathematical prose here would silently turn text into Lean syntax.  If a
    context item is not formalized, the data projection remains available but no axiom is emitted.
    """

    rendered_conclusion = _lean_proposition(conclusion)
    if rendered_conclusion is None:
        return None
    if not context:
        return rendered_conclusion
    rendered_context: list[str] = []
    for statement in context:
        rendered = _lean_proposition(statement)
        if rendered is None:
            return None
        rendered_context.append(rendered)
    return " → ".join(f"({item})" for item in (*rendered_context, rendered_conclusion))


def _lean_name(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not normalized or normalized[0].isdigit():
        normalized = f"id_{normalized}"
    return normalized


def _require_unique_generated_names(
    obligations: tuple[ProofObligation, ...],
    claims: tuple[Claim, ...],
) -> None:
    for label, identifiers in (
        ("proof obligation", tuple(item.id for item in obligations)),
        ("claim", tuple(item.id for item in claims)),
    ):
        names: dict[str, str] = {}
        for identifier in identifiers:
            generated = _lean_name(identifier)
            prior = names.get(generated)
            if prior is not None:
                raise ValueError(
                    f"{label} IDs {prior!r} and {identifier!r} produce duplicate Lean name "
                    f"{generated!r}"
                )
            names[generated] = identifier


def _lean_string(value: str) -> str:
    escaped: list[str] = []
    replacements = {
        "\\": "\\\\",
        '"': '\\"',
        "\n": "\\n",
        "\r": "\\x0d",
        "\t": "\\t",
    }
    for character in value:
        replacement = replacements.get(character)
        if replacement is not None:
            escaped.append(replacement)
        elif ord(character) < 0x20 or ord(character) == 0x7F:
            escaped.append(f"\\x{ord(character):02x}")
        else:
            escaped.append(character)
    return "".join(escaped)


def _lean_string_list(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(f'"{_lean_string(value)}"' for value in values) + "]"


def _lean_statement_text_list(values: tuple[object, ...]) -> str:
    texts: list[str] = []
    for value in values:
        text = getattr(value, "text", None)
        if not isinstance(text, str):
            raise TypeError("Lean statement metadata requires statement-like values")
        texts.append(text)
    return _lean_string_list(tuple(texts))


def _lean_optional_string(value: str | None) -> str:
    if value is None:
        return "none"
    return f'some "{_lean_string(value)}"'


def _comment(value: str) -> str:
    return value.replace("\n", " ").replace("-/", "- / ")


__all__ = ["export_lean"]
