"""Certified finite-exact deformation complexes, spaces, and lifts."""

from __future__ import annotations

from .certificate import (
    PORTABLE_VERIFIER,
    ArtinMapCertificate,
    ArtinRingCertificate,
    DeformationCertificateError,
    DeformationComplexCertificate,
    DeformationReceipt,
    DeformationSpaceCertificate,
    EquivarianceCertificate,
    FramingCertificate,
    LiftCertificate,
    RigidityCertificate,
    SmallExtensionCertificate,
    verify_deformation_receipt,
)
from .complex import DeformationComplex
from .equivariant import (
    DeformationAction,
    EquivariantComponent,
    EquivariantDecomposition,
    EquivariantDeformation,
    InvariantDeformations,
    equivariant,
    equivariant_decomposition,
    invariant_deformations,
)
from .errors import (
    DeformationError,
    DeformationVerificationError,
    UnsupportedDeformation,
    UnsupportedDeformationOperation,
)
from .framing import Framing, frame
from .lifting import (
    ContractionCertificate,
    FixedLift,
    FixedLiftResult,
    LiftDatum,
    LiftEndomorphism,
    LiftFamily,
    LiftObstructed,
    LiftResult,
    LiftUnknown,
    NonUniqueLift,
    UniqueLift,
    UniqueLiftResult,
    fixed_lift,
    lift,
    unique_lift,
)
from .problem import (
    DeformationPresentation,
    DeformationProblem,
    GaugeSpace,
    NonRigid,
    ObstructionClass,
    ObstructionSpace,
    Rigid,
    RigidityResult,
    TangentSpace,
    deformation_problem,
    gauge,
    obstructions,
    rigid,
    tangent,
)
from .rings import ArtinRing, ArtinRingElement, ArtinRingMap, SmallExtension
from .semantic import (
    claim_for_result,
    claim_graph_for_result,
    verification_certificate_for_result,
)

__all__ = [
    "PORTABLE_VERIFIER",
    "ArtinMapCertificate",
    "ArtinRing",
    "ArtinRingCertificate",
    "ArtinRingElement",
    "ArtinRingMap",
    "ContractionCertificate",
    "DeformationAction",
    "DeformationCertificateError",
    "DeformationComplex",
    "DeformationComplexCertificate",
    "DeformationError",
    "DeformationPresentation",
    "DeformationProblem",
    "DeformationReceipt",
    "DeformationSpaceCertificate",
    "DeformationVerificationError",
    "EquivarianceCertificate",
    "EquivariantComponent",
    "EquivariantDecomposition",
    "EquivariantDeformation",
    "FixedLift",
    "FixedLiftResult",
    "Framing",
    "FramingCertificate",
    "GaugeSpace",
    "InvariantDeformations",
    "LiftCertificate",
    "LiftDatum",
    "LiftEndomorphism",
    "LiftFamily",
    "LiftObstructed",
    "LiftResult",
    "LiftUnknown",
    "NonRigid",
    "NonUniqueLift",
    "ObstructionClass",
    "ObstructionSpace",
    "Rigid",
    "RigidityCertificate",
    "RigidityResult",
    "SmallExtension",
    "SmallExtensionCertificate",
    "TangentSpace",
    "UniqueLift",
    "UniqueLiftResult",
    "UnsupportedDeformation",
    "UnsupportedDeformationOperation",
    "claim_for_result",
    "claim_graph_for_result",
    "deformation_problem",
    "equivariant",
    "equivariant_decomposition",
    "fixed_lift",
    "frame",
    "gauge",
    "invariant_deformations",
    "lift",
    "obstructions",
    "rigid",
    "tangent",
    "unique_lift",
    "verification_certificate_for_result",
    "verify_deformation_receipt",
]
