"""Exact deterministic linear algebra over prime finite fields."""

from __future__ import annotations

from .algorithms import (
    LinearSolveResult,
    LinearSubspace,
    QuotientSpace,
    RREFResult,
    column_space,
    complement,
    determinant,
    image,
    intersection,
    inverse,
    kernel,
    left_nullspace,
    nullspace,
    quotient,
    quotient_space,
    rank,
    row_space,
    rref,
    solve,
    sum_subspaces,
)
from .errors import (
    DimensionMismatchError,
    FieldMismatchError,
    LinearAlgebraError,
    SingularMatrixError,
)
from .field import FieldElement, FiniteField, PrimeField, PrimeFieldElement, Scalar
from .matrix import DenseMatrix, Matrix, SparseMatrix, Vector, as_dense

__all__ = [
    "DenseMatrix",
    "DimensionMismatchError",
    "FieldElement",
    "FieldMismatchError",
    "FiniteField",
    "LinearAlgebraError",
    "LinearSolveResult",
    "LinearSubspace",
    "Matrix",
    "PrimeField",
    "PrimeFieldElement",
    "QuotientSpace",
    "RREFResult",
    "Scalar",
    "SingularMatrixError",
    "SparseMatrix",
    "Vector",
    "as_dense",
    "column_space",
    "complement",
    "determinant",
    "image",
    "intersection",
    "inverse",
    "kernel",
    "left_nullspace",
    "nullspace",
    "quotient",
    "quotient_space",
    "rank",
    "row_space",
    "rref",
    "solve",
    "sum_subspaces",
]
